services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Str0ngP@ssw0rd!
      MYSQL_DATABASE: edu_docker_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Str0ngP@ssw0rd!
      DB_NAME: edu_docker_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

volumes:
  mysql_data:
